import type { Metadata } from "next";
import { Inter, Roboto, Source_Code_Pro, Poiret_One } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/NavigationBar";
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: "400", subsets: ["latin"] });
const codepro = Source_Code_Pro({ weight: "400", subsets: ["latin"] });
const poi = Poiret_One({ weight: "400", subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={codepro.className + " bg-lime-200 scroll-smooth"}>
        <NavigationBar className={"bg-green-500 font-extrabold " + codepro.className} />
        {children}<Analytics/></body>
    </html>
  );
}
